DatabaseDirectory /var/lib/clamav
LocalSocket /work/clamd.sock
FixStaleSocket yes
User downloader
Foreground yes
LogTime yes
MaxThreads 2
MaxQueue 4
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 120
StreamMaxLength 68M
MaxFileSize 2G
MaxScanSize 2G
PCREMaxFileSize 2G
MaxScanTime 0
MaxRecursion 16
MaxFiles 10000
MaxEmbeddedPE 64M
MaxPartitions 64
MaxIconsPE 100
PCREMatchLimit 50000
PCRERecMatchLimit 5000
BytecodeTimeout 5000
AlertEncrypted yes
AlertExceedsMax yes
